# This is a basic workflow to help you get started with Actions

name: Trigerring the workflow_dispatch using Inputs
on:
  workflow_dispatch:
    inputs:
      run-test:
        description: Weather to run or not
        type: boolean
        required: true
        default: false
      test-type:
        description: What will be test type?
        type: choice
        options:
          - sandbox
          - unit
          - pre-production
          - production
          - all
        required: true
      environment:
        description: Current environment?
        required: false
        type: boolean
      build_No:
        description: What is Build No?
        type: number
        required: true
      comment:
        description: Any Message?
        required: false
        type: string

jobs:
  printing_the_inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Printing_all_the_inputs
        run: |
          echo " Printing the Run Test  : ${{inputs.run-test}}"
          echo " Printing the  Test Type : ${{inputs.test-type}}"
          echo " Printing the Current Environment  : ${{inputs.environment}}"
          echo " Printing the  Build No. : ${{inputs.build_No}}"
          echo " Printing the  Message/Comment : ${{inputs.comment}}"
      - name: Run_Test
        if: ${{inputs.test-type}} == pre-production
        run: |
         echo "Running the Plan"
         echo "Terraform fmt"
         echo "Terraform validate"
         echo "Terraform paln"
      
         - name: Deployment
         if: ${{inputs.test-type}} == production
         run: |
          echo "Running the Plan"
          echo "Terraform fmt"
          echo "Terraform validate"
          echo "Terraform paln"
         

  
